# Generated by Django 5.1.4 on 2025-02-12 12:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst_pytania', models.CharField(max_length=200)),
                ('data_pub', models.DateTimeField(default=datetime.date.today, verbose_name='data publikacji')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Odpowiedz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst_odp', models.CharField(max_length=200)),
                ('glosy', models.IntegerField(default=0)),
                ('pytanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pytanie')),
            ],
        ),
    ]
