# Generated by Django 5.2.4 on 2025-09-16 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('czat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiadomosc',
            name='data_pub',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data publikacji'),
        ),
    ]
